class OriginalDocDataConstanstsMixin:
    # flake8: noqa: C901
    CUSTOM_HEADER_MAP = {
        "percentage-of-employed-population-by-district-and-major-groups-of-industry": [
            "district",
            "total-employed-population",
            "agriculture-and-forestry",
            "fishing",
            "mining-and-quarrying",
            "manufacturing",
            "electricity-gas-and-water-supply",
            "construction",
            "wholesale-and-retail-trade",
            "hotels-and-restaurants",
            "transport-storage-and-communication",
            "financial-intermediation",
            "real-estate-renting-and-business-activities",
            "public-administration-and-defence-compulsory-social-security",
            "education",
            "health-and-social-work",
            "other-community-social-and-personal-service-activities",
            "private-households-with-employed-persons",
        ],
        "population-by-district-5-year-age-groups-and-sex": [
            "district",
            "total-population",
            "0-4",
            "5-9",
            "10-14",
            "15-19",
            "20-24",
            "25-29",
            "30-34",
            "35-39",
            "40-44",
            "45-49",
            "50-54",
            "55-59",
            "60-64",
            "65-69",
            "70-74",
            "75-and-over",
        ],
        "number-and-percentage-of-population-by-district-and-sector": [
            "district",
            "total-population",
            "population-in-urban-sector-no",
            "population-in-urban-sector",
            "population-in-rural-sector-no",
            "population-in-rural-sector",
            "population-in-estate-sector-no",
            "population-in-estate-sector",
        ],
        "number-and-percentage-of-population-by-district-and-religion": [
            "district",
            "total-population",
            "buddhist-no",
            "buddhist",
            "hindu-no",
            "hindu",
            "islam-no",
            "islam",
            "roman-catholic-no",
            "roman-catholic",
            "other-no",
            "other",
        ],
        "percentage-of-population-aged-10-years-and-over-in-major-ethnic-groups-by-district-and-ability-to-speak-sinhala-tamil-and-english-languages": [
            "district",
            "sinhalese-population-sinhala-language",
            "sinhalese-population-english-language",
            "sri-lanka-tamil-population-tamil-language",
            "sri-lanka-tamil-population-english-language",
            "sri-lanka-tamil-population-sinhala-language",
            "indian-tamil-population-english-language",
            "indian-tamil-population-sinhala-language",
            "sri-lanka-moor-population-english-language",
        ],
        "percentage-of-children-aged-614-years-not-attending-school-by-district-and-sector": [
            "district",
            "total",
            "urban",
            "rural",
            "estate",
        ],
        "percentage-of-population-aged-5-years-and-over-by-district-and-educational-attainment": [
            "district",
            "population-aged-5-years-and-over",
            "percentage-of-population-completed-primary-education-passed-year-1-5",
            "percentage-of-population-completed-lower-secondary-passed-year-6-8",
            "percentage-of-population-completed-upper-secondary-passed-year-9-11",
            "percentage-of-population-completed-tertiary-education-passed-gce-al-above",
        ],
        "percentage-of-employed-population-by-districtemployment-status-and-employment-sector": [
            "district",
            "total-employed-population-aged-10-years-and-over",
            "government-employees",
            "semi-government-employees",
            "private-sector-employees-and-employers",
            "own-account-workers",
            "unpaid-family-workers",
        ],
        "number-and-percentage-of-agricultural-and-fishery-workers-and-nonagricultural-and-fishery-workers-by-district": [
            "district",
            "total-employed-population-aged-10-years-and-over",
            "agricultural-and-fishery-workers-including-unskilled-labourers-no",
            "agricultural-and-fishery-workers-including-unskilled-labourers",
            "non-agricultural-and-fishery-workers-no",
            "non-agricultural-and-fishery-workers",
        ],
        "percentage-of-employed-population-in-agricultural-and-fishery-sector-by-district-and-sub-groups-of-occupation": [
            "district",
            "total-employed-population-aged-10-years-and-over",
            "agricultural-and-fishery-workers-including-unskilled-labourers-no",
            "agricultural-and-fishery-workers-including-unskilled-labourers",
            "non-agricultural-and-fishery-workers-no",
            "non-agricultural-and-fishery-workers",
        ],
        "populationresident-since-birth-migrants-and-duration-of-residence-by-district-of-usual-residence": [
            "district",
            "total-agricultural-and-fishery-workers-including-unskilled-labourers-engaged-in-agricultural-and-fishery-sector",
            "market-gardeners-and-crop-growers",
            "market-oriented-animal-producers",
            "market-oriented-crop-and-animal-producers",
            "forestry-and-related-workers",
            "fishery-workers-hunters-and-trappers",
            "subsistence-agricultural-and-fishery-workers",
            "subsistence-dairy-livestock-and-related-workers",
        ],
        "number-and-percentage-of-occupied-housing-units-by-district-and-type-of-housing-unit": [
            "district",
            "total-occupied-housing-units",
            "permanent-no",
            "permanent",
            "semi-permanent-no",
            "semi-permanent",
            "improvised-no",
            "improvised",
        ],
    }

    def get_custom_headers(self):
        return self.CUSTOM_HEADER_MAP.get(self.doc_id, None)
